"""The README GitHub renders under a map folder.

A folder of JSON files tells a browsing human nothing, so each map folder gets a
README with a picture, the facts, and every version linked. GitHub renders one
under any directory listing, which is what makes the archive browsable without
anything being installed.

**This module does not draw anything.** The editor renders previews and bundles
them with the map - it owns the icons and whatever sprite pack is loaded, so it
can draw a real picture where a second renderer here could only ever manage flat
blocks, and would have to be kept in step with the first forever. `awrbc
publish` keeps the image the editor made; this decides how it is presented.

The consequence, which is deliberate: a map published without going through the
editor has no preview, and its README simply has no image rather than a broken
one. The fix for that is to open the map in the editor and use Export bundle,
which is what anyone who cares how their map looks will do anyway.
"""
from . import archive


def preview_file(version):
    return "v%d.png" % version


def readme(entry, previews=None):
    """Build the folder README.

    Built from the catalog entry rather than from the map files, so it says the
    same thing the index does - a README that disagreed with the catalog beside
    it would be worse than no README.

    ``previews`` is the set of version numbers that actually have an image. When
    it is None every version is assumed to have one, which is what a caller
    generating a README for a single known-good map wants.
    """
    versions = sorted(entry.get("versions", []),
                      key=lambda v: v["version"], reverse=True)
    name = entry.get("name") or entry.get("slug", "")
    lines = ["# %s" % name, ""]

    # The newest version that has a picture - not simply the newest, or a map
    # whose latest revision was published without one would lose its preview
    # entirely rather than keep showing the last good picture of itself.
    shown = next((v for v in versions
                  if previews is None or v["version"] in previews), None)
    latest = versions[0] if versions else {}

    if shown:
        lines += ["![%s](%s)" % (name, preview_file(shown["version"]))]
        if shown is not latest:
            lines += ["", "<sub>Preview is of v%d; v%d was published without "
                          "one.</sub>" % (shown["version"], latest["version"])]
        lines += [""]

    if latest:
        facts = ["%d player%s" % (latest["players"],
                                  "" if latest["players"] == 1 else "s"),
                 "%dx%d" % (latest["cols"], latest["rows"])]
        for key in ("predeployed", "navy", "structures", "fog"):
            if latest.get(key):
                facts.append(key)
        lines += [" · ".join(facts), ""]

    author = entry.get("author")
    if author:
        lines += ["By **%s**" % author, ""]
    if latest.get("tags"):
        lines += ["Tagged %s" % ", ".join("`%s`" % t for t in latest["tags"]),
                  ""]

    lines += ["| Version | Added | Download |", "|---|---|---|"]
    for v in versions:
        lines.append("| v%d | %s | [%s](%s) |"
                     % (v["version"], v.get("added", ""),
                        archive.version_file(v["version"]),
                        archive.version_file(v["version"])))
    lines += ["",
              "*This file is generated by `awrbc catalog`; edits here are "
              "overwritten. The preview comes from the map editor.*", ""]
    return "\n".join(lines)


# --- Checking a preview somebody else made ----------------------------------
#
# The image arrives from outside and is copied into a public repository, so it
# gets checked like any other untrusted input.
#
# What this cannot do is confirm the picture *is* the map - only a renderer
# could, and the one that drew it lives in the browser. What it can do is make
# the file be a plain PNG of exactly the size that map must produce, which
# removes the whole class of "arbitrary file wearing a .png name".
#
# A secret stamped into the header by the editor would add nothing: the editor
# is a static page, so the secret ships to everyone who loads it. Signing only
# means something where the key can be kept, which is the intake endpoint
# (decision #28), not the browser.

import binascii
import struct

from .validate import ERROR, WARNING, Report

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

#: Pixels per tile the editor renders a bundled preview at. Must match
#: PREVIEW_TILE in web/index.html; tests/test_preview_check.py pins that.
PREVIEW_TILE = 16

#: A 64x64 map at 16px is 1024x1024 of flat colour. Well under this.
MAX_PREVIEW_BYTES = 2 * 1024 * 1024

#: Chunks a canvas-produced PNG actually contains. Anything else is not
#: necessarily an attack, but it is not something the editor emits, and a
#: preview is not a place to carry extra payload.
EXPECTED_CHUNKS = frozenset([b"IHDR", b"PLTE", b"IDAT", b"IEND", b"pHYs",
                             b"sRGB", b"gAMA", b"cHRM", b"iCCP", b"bKGD",
                             b"tRNS"])


def _walk_chunks(data):
    """Yield (tag, payload, crc_ok, end) up to and including IEND.

    Stops there rather than reading on, because everything after IEND is not
    malformed chunks - it is a different file. The caller measures what is left
    and says so, which is a far more useful answer than "chunk runs past the
    end". Raises ValueError on a stream that is genuinely malformed.
    """
    pos = len(PNG_MAGIC)
    while pos < len(data):
        if pos + 8 > len(data):
            raise ValueError("truncated chunk header")
        (length,) = struct.unpack(">I", data[pos:pos + 4])
        tag = data[pos + 4:pos + 8]
        end = pos + 12 + length
        # Checked against the real length first: the size field is
        # attacker-controlled, and 0x7FFFFFFF must not become an allocation.
        if length > len(data) or end > len(data):
            raise ValueError("chunk %r runs past the end of the file"
                             % tag.decode("ascii", "replace"))
        payload = data[pos + 8:pos + 8 + length]
        (want,) = struct.unpack(">I", data[end - 4:end])
        yield (tag, payload,
               (binascii.crc32(tag + payload) & 0xFFFFFFFF) == want, end)
        if tag == b"IEND":
            return
        pos = end


def check_png(data, m=None, tiles=None):
    """Whether this is a plain PNG, and the one this map would produce.

    The expected size comes from ``m``, or from ``tiles`` as ``(cols, rows)``
    when the caller has the dimensions but not the map - which is the case in
    CI, where the catalog records them and re-parsing every map to check an
    image would be wasteful. Neither: the structural checks still run.
    """
    if tiles is None and m is not None:
        tiles = (m.cols, m.rows)
    r = Report()
    if not data.startswith(PNG_MAGIC):
        r.add("preview.notPng", ERROR,
              "preview is not a PNG; the first bytes are %r"
              % data[:8], "preview")
        return r
    if len(data) > MAX_PREVIEW_BYTES:
        r.add("preview.tooLarge", ERROR,
              "preview is %d bytes; the cap is %d"
              % (len(data), MAX_PREVIEW_BYTES), "preview")

    tags, header, finished = [], None, None
    try:
        for tag, payload, crc_ok, end in _walk_chunks(data):
            tags.append(tag)
            if not crc_ok:
                r.add("preview.badChunk", ERROR,
                      "chunk %r fails its own checksum"
                      % tag.decode("ascii", "replace"), "preview")
            if tag == b"IHDR":
                header = payload
            elif tag == b"IEND":
                finished = end
    except ValueError as exc:
        r.add("preview.malformed", ERROR, str(exc), "preview")
        return r

    saw_end = finished is not None
    if saw_end and finished < len(data):
        # Data after IEND is the classic way to hide one file inside another.
        # A PNG that displays perfectly well can still carry a whole zip.
        r.add("preview.trailingData", ERROR,
              "%d bytes follow the end of the image"
              % (len(data) - finished), "preview")
    if not tags or tags[0] != b"IHDR":
        r.add("preview.malformed", ERROR, "no IHDR where one must be",
              "preview")
        return r
    if not saw_end:
        r.add("preview.malformed", ERROR, "no IEND; the file is truncated",
              "preview")
        return r

    unexpected = sorted({t.decode("ascii", "replace") for t in tags
                         if t not in EXPECTED_CHUNKS})
    if unexpected:
        r.add("preview.extraChunks", WARNING,
              "carries chunks the editor does not emit: %s"
              % ", ".join(unexpected), "preview")

    width, height = struct.unpack(">II", header[:8])
    if tiles is not None:
        cols, rows = tiles
        want = (cols * PREVIEW_TILE, rows * PREVIEW_TILE)
        if (width, height) != want:
            # The strongest tie there is between the picture and the map
            # without re-rendering: the editor draws one tile at a fixed size,
            # so a map of this size can produce exactly one image size. It does
            # not prove the picture is of this map - nothing here can - but an
            # arbitrary image has to be resized to the pixel to get through.
            r.add("preview.wrongSize", ERROR,
                  "preview is %dx%d; a %dx%d map renders %dx%d"
                  % (width, height, cols, rows, want[0], want[1]), "preview")
    return r
