"""The README GitHub renders under a map folder.

A folder of JSON files tells a browsing human nothing, so each map folder gets a
README with a picture, the facts, and every version linked. GitHub renders one
under any directory listing, which is what makes the archive browsable without
anything being installed.

**This module does not draw anything.** The editor renders previews and bundles
them with the map - it owns the icons and whatever sprite pack is loaded, so it
can draw a real picture where a second renderer here could only ever manage flat
blocks, and would have to be kept in step with the first forever. `awrbc
publish` keeps the image the editor made; this decides how it is presented.

The consequence, which is deliberate: a map published without going through the
editor has no preview, and its README simply has no image rather than a broken
one. The fix for that is to open the map in the editor and use Export bundle,
which is what anyone who cares how their map looks will do anyway.
"""
from . import archive


def preview_file(version):
    return "v%d.png" % version


def readme(entry, folder, previews=None):
    """Build the folder README.

    Built from the catalog entry rather than from the map files, so it says the
    same thing the index does - a README that disagreed with the catalog beside
    it would be worse than no README.

    ``previews`` is the set of version numbers that actually have an image. When
    it is None every version is assumed to have one, which is what a caller
    generating a README for a single known-good map wants.
    """
    versions = sorted(entry.get("versions", []),
                      key=lambda v: v["version"], reverse=True)
    name = entry.get("name") or entry.get("slug", "")
    lines = ["# %s" % name, ""]

    # The newest version that has a picture - not simply the newest, or a map
    # whose latest revision was published without one would lose its preview
    # entirely rather than keep showing the last good picture of itself.
    shown = next((v for v in versions
                  if previews is None or v["version"] in previews), None)
    latest = versions[0] if versions else {}

    if shown:
        lines += ["![%s](%s)" % (name, preview_file(shown["version"]))]
        if shown is not latest:
            lines += ["", "<sub>Preview is of v%d; v%d was published without "
                          "one.</sub>" % (shown["version"], latest["version"])]
        lines += [""]

    if latest:
        facts = ["%d player%s" % (latest["players"],
                                  "" if latest["players"] == 1 else "s"),
                 "%dx%d" % (latest["cols"], latest["rows"])]
        for key in ("predeployed", "navy", "structures", "fog"):
            if latest.get(key):
                facts.append(key)
        lines += [" · ".join(facts), ""]

    author = entry.get("author")
    if author:
        lines += ["By **%s**" % author, ""]
    if latest.get("tags"):
        lines += ["Tagged %s" % ", ".join("`%s`" % t for t in latest["tags"]),
                  ""]

    lines += ["| Version | Added | Download |", "|---|---|---|"]
    for v in versions:
        lines.append("| v%d | %s | [%s](%s) |"
                     % (v["version"], v.get("added", ""),
                        archive.version_file(v["version"]),
                        archive.version_file(v["version"])))
    lines += ["",
              "*This file is generated by `awrbc catalog`; edits here are "
              "overwritten. The preview comes from the map editor.*", ""]
    return "\n".join(lines)
